data_path: 'data/vrep'  # directory to save acquired data
dump_rt: True  # whether to dump data on-the-fly
robot_name: 'UR10_target'
cam_names: ['Vision_sensor', 'Vision_sensor0', 'Vision_sensor1', 'Vision_sensor2']
target_name: 'UR10_link6_visible'
