# wait
model: 'tless_01'
model_dir: 'data/model'
network: 'res'
heads: ''
task: 'pvnet'
resume: true
cls_type: '01'

train:
    optim: 'adam'
    lr: 1e-3
    epoch: 240
    milestones: (20, 40, 60, 80, 100, 120, 160, 180, 200, 220)
    gamma: 0.5
    batch_size: 40
    dataset: 'TlessPoseTrain'
    cropresize_rate: 1.0
    rotate_rate: 1.0
    rotate_min: -30
    rotate_max: 30
    weight_decay: 0.
test:
    dataset: 'TlessPoseTest'
    batch_size: 1
