# wait
model: 'tless_20'
model_dir: 'data/model'
network: 'res'
heads: ''
task: 'pvnet'
resume: true
cls_type: '020'

ep_iter: 500
gpus: [0, 1, 2, 3]

train:
    optim: 'adam'
    lr: 1e-3
    epoch: 240
    milestones: (20, 40, 60, 80, 100, 120, 160, 180, 200, 220)
    gamma: 0.5
    batch_size: 64
    dataset: 'TlessPoseTrain'
    cropresize_rate: 1.0
    rotate_rate: 1.0
    rotate_min: -30
    rotate_max: 30
    weight_decay: 0.
    num_workers: 32
test:
    dataset: 'TlessPoseTest'
    batch_size: 1
tless:
    pvnet_input_scale: (128, 128)
    scale_train_ratio: (1, 2)
    scale_ratio: 1.2
    box_train_ratio: (1.0, 1.2)
    box_ratio: 1.1
